// Generated by scripts/generate-ekadasi.mjs — do not edit by hand.
// Source: drik-siddhānta computation (same method as ISKCON GCal) with
// Lahiri ayanamsa and sunrise reference at Bangalore (12.9716, 77.5946).
// Handles kshaya / vridhi Ekadasi and Adhika Masa (Padmini & Parama).

export interface EkadasiEntry {
  date: string;
  name: string;
  sanskrit: string;
  month: string;
  paksha: 'Shukla' | 'Krishna';
}

export const ekadasi2026: EkadasiEntry[] = [
  {
    "date": "2026-01-14",
    "name": "Saphala",
    "sanskrit": "सफला",
    "month": "Pausha",
    "paksha": "Krishna"
  },
  {
    "date": "2026-01-29",
    "name": "Jaya",
    "sanskrit": "जया",
    "month": "Magha",
    "paksha": "Shukla"
  },
  {
    "date": "2026-02-13",
    "name": "Shattila",
    "sanskrit": "षट्तिला",
    "month": "Magha",
    "paksha": "Krishna"
  },
  {
    "date": "2026-02-27",
    "name": "Amalaki",
    "sanskrit": "आमलकी",
    "month": "Phalguna",
    "paksha": "Shukla"
  },
  {
    "date": "2026-03-15",
    "name": "Vijaya",
    "sanskrit": "विजया",
    "month": "Phalguna",
    "paksha": "Krishna"
  },
  {
    "date": "2026-03-29",
    "name": "Kamada",
    "sanskrit": "कामदा",
    "month": "Chaitra",
    "paksha": "Shukla"
  },
  {
    "date": "2026-04-13",
    "name": "Papamochani",
    "sanskrit": "पापमोचनी",
    "month": "Chaitra",
    "paksha": "Krishna"
  },
  {
    "date": "2026-04-27",
    "name": "Mohini",
    "sanskrit": "मोहिनी",
    "month": "Vaishakha",
    "paksha": "Shukla"
  },
  {
    "date": "2026-05-13",
    "name": "Varuthini",
    "sanskrit": "वरूथिनी",
    "month": "Vaishakha",
    "paksha": "Krishna"
  },
  {
    "date": "2026-05-27",
    "name": "Padmini",
    "sanskrit": "पद्मिनी",
    "month": "Adhika (Adhika)",
    "paksha": "Shukla"
  },
  {
    "date": "2026-06-11",
    "name": "Parama",
    "sanskrit": "परमा",
    "month": "Adhika (Adhika)",
    "paksha": "Krishna"
  },
  {
    "date": "2026-06-25",
    "name": "Nirjala",
    "sanskrit": "निर्जला",
    "month": "Jyeshtha",
    "paksha": "Shukla"
  },
  {
    "date": "2026-07-11",
    "name": "Apara",
    "sanskrit": "अपरा",
    "month": "Jyeshtha",
    "paksha": "Krishna"
  },
  {
    "date": "2026-07-25",
    "name": "Devshayani",
    "sanskrit": "देवशयनी",
    "month": "Ashadha",
    "paksha": "Shukla"
  },
  {
    "date": "2026-08-09",
    "name": "Yogini",
    "sanskrit": "योगिनी",
    "month": "Ashadha",
    "paksha": "Krishna"
  },
  {
    "date": "2026-08-23",
    "name": "Putrada",
    "sanskrit": "पुत्रदा",
    "month": "Shravana",
    "paksha": "Shukla"
  },
  {
    "date": "2026-09-07",
    "name": "Kamika",
    "sanskrit": "कामिका",
    "month": "Shravana",
    "paksha": "Krishna"
  },
  {
    "date": "2026-09-22",
    "name": "Parsva",
    "sanskrit": "पार्श्व",
    "month": "Bhadrapada",
    "paksha": "Shukla"
  },
  {
    "date": "2026-10-06",
    "name": "Aja",
    "sanskrit": "अजा",
    "month": "Bhadrapada",
    "paksha": "Krishna"
  },
  {
    "date": "2026-10-22",
    "name": "Papankusha",
    "sanskrit": "पापांकुशा",
    "month": "Ashwin",
    "paksha": "Shukla"
  },
  {
    "date": "2026-11-05",
    "name": "Indira",
    "sanskrit": "इन्दिरा",
    "month": "Ashwin",
    "paksha": "Krishna"
  },
  {
    "date": "2026-11-21",
    "name": "Prabodhini",
    "sanskrit": "प्रबोधिनी",
    "month": "Kartik",
    "paksha": "Shukla"
  },
  {
    "date": "2026-12-04",
    "name": "Rama",
    "sanskrit": "रमा",
    "month": "Kartik",
    "paksha": "Krishna"
  },
  {
    "date": "2026-12-20",
    "name": "Mokshada",
    "sanskrit": "मोक्षदा",
    "month": "Margashirsha",
    "paksha": "Shukla"
  }
];
